### ISSUE TITLE
Installation instructions clarification, additional options

### ISSUE THREAD

**Issue by opconWizard** [SMATechnologies/usage-data#2]
* The instructions say to unzip the winbase.zip to the "SAM" installation folder but its not clear if it means "ProgramData" or "Program Files".  

* There is no mention of the global property "SMAOpConPath" used in the job which could lead to issues in various environments.  Does this get created if it does not already exist?  

~~* There should also be an option to have the schedule auto-delete as the default currently does not.~~. Split to https://github.com/SMATechnologies/usage-data/issues/3.

~~* The output files are lost within all the dlls/installation files, having them go to a different folder would make it cleaner (or at least adding the option of an output path for local).~~. Split to https://github.com/SMATechnologies/usage-data/issues/4.

**Comment by ryandimick** [comment]
@adesaisma / @opconWizard - my vote for the first item would be we just use an example.  Installation location is the common term we use to always reference the application file directory, which may or may not be in a Program Files directory (e.g. E:\OpCon).

**Comment by aydesai** [comment]
Thank you for the comments and suggestions @opconWizard and @ryandimick. So as far as SMAOpConPath is concerned, we don't create it, but may be a good idea. Also the auto delete and output location (this last one, we wanted to but somehow never implemented).

I'll fix the instructions accordingly. We can do another release with the ideas, and it will self update. But of course they would need some updates to the job to really use them - like custom output location.
